apiVersion: v1
kind: Secret
metadata:
  name: jfrogcred
  namespace: arunim
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJhcnVuaW0uamZyb2cuaW8iOiB7CgkJCSJhdXRoIjogIlpHOWphMlZ5WTNKbFpEcERaRzFoWW5SbFkyZ3FNVFV4TVE9PSIKCQl9Cgl9Cn0=
type: kubernetes.io/dockerconfigjson
