apiVersion: v1
kind: Service
metadata:
  name: arunim-rtp-service
  namespace: arunim
spec:
  type: NodePort
  selector:
    app: arunim-rtp
  ports:
    - nodePort: 30082
      port: 8000
      targetPort: 8000
